includes:
  - dynamic-plugins.default.yaml
plugins:
  - package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
    disabled: false

  - disabled: false
    package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic

  # Enable Bulk import plugins.
  - package: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-bulk-import-backend:pr_1271__6.1.5!red-hat-developer-hub-backstage-plugin-bulk-import-backend"
    disabled: false
  - package: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-bulk-import:pr_1271__1.13.4!red-hat-developer-hub-backstage-plugin-bulk-import"
    disabled: false
